### PR TITLE
Telegram Bot

### PR DESCRIPTION
**Pull request by sneeu-leeu**
### In this capstone I :
- Created a bot for Telegram
- Wrote RSpect tests to test the code
- Used APIs to build functionality
- Used Ruby gems

### Rspec tests all pass locally, error due to a problem in my rbenv that I can not seem to solve. Running suggested commands by Github Rspec cause further harm. photo of passing tests posted in comments.

### CODE REVIEW

**Comment by sneeu-leeu** [comment]
Screenshot from 2020-11-22 09-52-50

**Comment by sneeu-leeu** [comment]
Screenshot from 2020-11-22 10-07-41

**Comment by SpaYco** [comment]
hello @sneeu-leeu, please use this code for `tests.yml` and it should work

```
name: Tests

on: pull_request

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Setup RSpec
        run: |
          gem install bundler
          [ -f Gemfile ] && bundle --deployment
          gem install --no-document rspec:'~>3.0'
      - name: RSpec Report
        run: rspec --force-color --format documentation
```

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Comment by sneeu-leeu** [comment]
Screenshot from 2020-11-22 22-16-14


The last review told me to add these extensions, Linters told me they are redundant. For sake of keeping reviewers happy, I have disabled these linters.

**Pull request merged**
